name: pio test

on:
  push:
    branches: [ unittest, develop, master ]
  pull_request:
    branches: [ unittest, develop, master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO Test
        run: platformio test -e native

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO Build
        run: platformio run -e d1_mini -e lolin32
        env:
          PLATFORMIO_BUILD_FLAGS: -D ESPFC_REVISION=${GITHUB_SHA::8}
      - name: Artifact espfc_d1_mini_${GITHUB_SHA::8}.bin
        uses: actions/upload-artifact@v1
        with:
          name: espfc_d1_mini_${GITHUB_SHA::8}.bin
          path: .pio/build/d1_mini/firmware.bin
      - name: Artifact espfc_lolin32_${GITHUB_SHA::8}.bin
        uses: actions/upload-artifact@v1
        with:
          name: espfc_lolin32_${GITHUB_SHA::8}.bin
          path: .pio/build/lolin32/firmware.bin
